image: node:latest

stages:
  - deploy

before_script:
  - git config user.email "edwin.dzemovski@ynov.com"
  - git config user.username "EdwinDz"


cache:
  paths:
    - node_modules/

deploy-to-prod:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=unitynov --api-key=$HEROKU_KEY
  only:
    - master

  artifacts:
    paths:
      - node_modules/
