image: node:latest

stages:
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: test
  script:
    - npm install
    - npm test

  artifacts:
    paths:
      - node_modules/
